const products=[
 {id:1,name:'تيشيرت البرق الأخضر',category:'shirts',label:'تيشيرتات',price:70,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=80',stock:true},
 {id:2,name:'تيشيرت الفريق الأبيض',category:'shirts',label:'تيشيرتات',price:70,image:'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=700&q=80',stock:true},
 {id:3,name:'حذاء ألترا رياضي',category:'shoes',label:'أحذية',price:230,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80',stock:true},
 {id:4,name:'سنيكرز ستريت كاجول',category:'casual',label:'كاجول',price:200,image:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=700&q=80',stock:false},
 {id:5,name:'تيشيرت أسود كلاسيك',category:'shirts',label:'تيشيرتات',price:70,image:'https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=700&q=80',stock:true},
 {id:6,name:'حذاء فاست ران',category:'shoes',label:'أحذية',price:250,image:'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=700&q=80',stock:true},
 {id:7,name:'هودي كاجول يومي',category:'casual',label:'كاجول',price:220,image:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=700&q=80',stock:true},
 {id:8,name:'تيشيرت المشجعين',category:'shirts',label:'تيشيرتات',price:70,image:'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=700&q=80',stock:true}
];
let active='all', visible=4, cart=[];
const grid=document.getElementById('productGrid');
function render(){let list=products.filter(p=>active==='all'||p.category===active).slice(0,visible);grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="tag ${p.stock?'':'sold'}">${p.stock?'متوفر':'انتهاء الكمية'}</span></div><div class="product-info"><span class="category">${p.label}</span><h3>${p.name}</h3>${p.stock?`<select class="size-select" id="size-${p.id}"><option value="S">المقاس: S</option><option value="M">المقاس: M</option><option value="L">المقاس: L</option><option value="XL">المقاس: XL</option></select>`:'<div class="size-select" style="color:#9aa">غير متوفر حالياً</div>'}<div class="price"><strong>${p.price} <small>ر.ق</small></strong><button class="add" onclick="addToCart(${p.id})" ${p.stock?'':'disabled'} aria-label="إضافة للسلة">+</button></div></div></article>`).join('');document.getElementById('moreButton').style.display=visible>=products.filter(p=>active==='all'||p.category===active).length?'none':'block'}
function addToCart(id){let p=products.find(x=>x.id===id),size=document.getElementById('size-'+id)?.value||'واحد';cart.push({...p,size});updateCart();document.getElementById('cartDrawer').classList.add('open');document.getElementById('overlay').classList.add('show')}
function updateCart(){document.getElementById('cartCount').textContent=cart.length;document.getElementById('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><span>${x.name}<small>المقاس: ${x.size}</small></span><b>${x.price} ر.ق <button onclick="removeItem(${i})" style="background:none;color:#999">×</button></b></div>`).join(''):'<p class="empty">السلة فارغة حالياً 🛍️</p>';document.getElementById('cartTotal').textContent=cart.reduce((a,x)=>a+x.price,0)+' ر.ق'}
function removeItem(i){cart.splice(i,1);updateCart()}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');active=b.dataset.filter;visible=4;render()});document.getElementById('moreButton').onclick=()=>{visible+=4;render()};document.getElementById('cartButton').onclick=()=>{document.getElementById('cartDrawer').classList.add('open');document.getElementById('overlay').classList.add('show')};function close(){document.getElementById('cartDrawer').classList.remove('open');document.getElementById('overlay').classList.remove('show')}document.getElementById('closeCart').onclick=close;document.getElementById('overlay').onclick=close;document.getElementById('checkout').onclick=()=>alert('شكراً لك! سيتواصل معك فريق E11store لتأكيد الطلب.');render();
